contact_links:
  - name: YAP user group
    url: https://groups.google.com/group/yaproxy-users
    about: Please ask and answer questions about using YAP here - do not raise issues for questions.
  - name: YAP developer group
    url: https://groups.google.com/group/yaproxy-develop
    about: Please ask and answer questions about YAP internals here.
  - name: YAP security bug bounty program
    url: https://bugcrowd.com/owaspyap
    about: Please report security vulnerabilities here.
