# syntax=docker/dockerfile:1
# This dockerfile builds a YAP docker image used for integration tests
FROM ghcr.io/yaproxy/yaproxy:nightly
LABEL maintainer="psiinon@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive

#Change to the yap user so things get done as the right person (apart from copy)
USER yap

COPY --link --chown=1000:1000 integration_tests /yap/wrk/

# Pick up any local changes
COPY --link --chown=1000:1000 yap* CHANGELOG.md /yap/

RUN chmod +x /yap/wrk/*.sh

WORKDIR /yap
