# syntax=docker/dockerfile:1
# This dockerfile builds the yap weekly release
FROM --platform=linux/amd64 debian:bullseye-slim AS builder
RUN apt-get update && apt-get install -q -y --fix-missing \
	wget \
	curl \
	unzip && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /yap

# Setup Webswing
ENV WEBSWING_VERSION 22.2.4
RUN --mount=type=secret,id=webswing_url \
	if [ -s /run/secrets/webswing_url ] ; \
	then curl -s -L  "$(cat /run/secrets/webswing_url)-${WEBSWING_VERSION}-distribution.zip" > webswing.zip; \
	else curl -s -L  "https://dev.webswing.org/files/public/webswing-examples-eval-${WEBSWING_VERSION}-distribution.zip" > webswing.zip; fi && \
	unzip webswing.zip && \
	rm webswing.zip && \
	mv webswing-* webswing && \
	# Remove Webswing bundled examples
	rm -Rf webswing/apps/

FROM debian:bullseye-slim AS final
LABEL maintainer="psiinon@gmail.com"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -q -y --fix-missing \
	make \
	automake \
	autoconf \
	gcc g++ \
	openjdk-11-jdk \
	wget \
	curl \
	xmlstarlet \
	unzip \
	git \
	openbox \
	xterm \
	net-tools \
	python3-pip \
	python-is-python3 \
	firefox-esr \
	xvfb \
	x11vnc && \
	rm -rf /var/lib/apt/lists/* && \
    useradd -u 1000 -d /home/yap -m -s /bin/bash yap && \
    echo yap:yap | chpasswd && \
    mkdir /yap  && \
    chown yap:yap /yap

RUN pip3 install --no-cache-dir --upgrade awscli pip yaproxy pyyaml requests urllib3

WORKDIR /yap

#Change to the yap user so things get done as the right person (apart from copy)
USER yap

RUN mkdir /home/yap/.vnc

RUN curl -s https://raw.githubusercontent.com/yaproxy/yap-admin/master/YapVersions.xml | xmlstarlet sel -t -v //url |grep -i weekly | wget --content-disposition -i - && \
	unzip *.zip && \
	rm *.zip && \
	cp -R YAP*/* . &&  \
	rm -R YAP*

ARG TARGETARCH
ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk-$TARGETARCH
ENV PATH $JAVA_HOME/bin:/yap/:$PATH
ENV YAP_PATH /yap/yap.sh

# Default port for use with health check
ENV YAP_PORT 8080
ENV IS_CONTAINERIZED true
ENV HOME /home/yap/
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY --link --chown=1000:1000 yap* CHANGELOG.md /yap/
COPY --link --from=builder --chown=1000:1000 /yap/webswing /yap/webswing
COPY --link --chown=1000:1000 webswing.config /yap/webswing/
COPY --link --chown=1000:1000 webswing.properties /yap/webswing/
COPY --link --chown=1000:1000 policies /home/yap/.YAP_D/policies/
COPY --link --chown=1000:1000 policies /root/.YAP_D/policies/
COPY --link --chown=1000:1000 scripts /home/yap/.YAP_D/scripts/
COPY --link --chown=1000:1000 .xinitrc /home/yap/

RUN echo "yap2docker-weekly" > /yap/container && \
    chmod a+x /home/yap/.xinitrc

HEALTHCHECK CMD curl --silent --output /dev/null --fail http://localhost:$YAP_PORT/ || exit 1
