# syntax=docker/dockerfile:1
# This dockerfile builds the yap bare release
FROM --platform=linux/amd64 debian:bullseye-slim AS builder

RUN apt-get update && apt-get install -q -y --fix-missing \
	wget \
	curl \
	openjdk-11-jdk \
	xmlstarlet \
	unzip && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /yap

# Download and expand the latest stable release
RUN wget -qO- https://raw.githubusercontent.com/yaproxy/yap-admin/master/YapVersions.xml | xmlstarlet sel -t -v //url |grep -i Linux | wget --content-disposition -i - -O - | tar zxv && \
	mv YAP*/* . && \
	rm -R YAP*

# Update add-ons
RUN ./yap.sh -cmd -silent -addonupdate
# Copy them to installation directory
RUN cp /root/.YAP/plugin/*.yap plugin/ || :

FROM eclipse-temurin:11-jre-alpine AS final
LABEL maintainer="psiinon@gmail.com"

RUN apk add --no-cache bash curl

USER root

WORKDIR /yap
COPY --from=builder --link --chown=1000:1000 /yap .
COPY --link --chown=1000:1000 policies /home/yap/.YAP/policies/

RUN echo "yap2docker-bare" > /yap/container

RUN /usr/sbin/adduser -u 1000 -h /home/yap -s /bin/bash -D yap

#Change to the yap user so things get done as the right person (apart from copy)
USER yap

ENV PATH $JAVA_HOME/bin:/yap/:$PATH
ENV YAP_PATH /yap/yap.sh
ENV HOME /home/yap/
ENV YAP_PORT 8080

HEALTHCHECK CMD curl --silent --output /dev/null --fail http://localhost:$YAP_PORT/ || exit 1
