name: Release Weekly

on:
  workflow_dispatch:

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        persist-credentials: false
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Build and Release
      env:
        YAPBOT_TOKEN: ${{ secrets.YAPBOT_TOKEN }}
        YAP_RELEASE: 1
        YAP_JAVA_VERSION: 11
      run: ./gradlew "-Dorg.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m" :yap:createWeeklyRelease
