name: Run Sonar

on:
  schedule:
    - cron: '30 15 * * SAT'
  workflow_dispatch:

jobs:
  sonar:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Gradle Test & Coverage Report
      run: ./gradlew test jacocoTestReport -Dorg.gradle.jvmargs=-Xmx4096m
    - name: Sonarcloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.YAPBOT_SONARCLOUD_TOKEN }}
      run: ./gradlew -Dorg.gradle.jvmargs=-Xmx4g sonar --stacktrace
